# ============================
#  CONFIGURAZIONE MQTT
# ============================
MQTTHOST=192.168.1.220
MQTTUSER=casa
MQTTPASWD=mosquitto1!casa

# Topic dove pubblicare i valori del BMS
TOPIC=seplosbms_v2/state

# Ogni quanti secondi inviare i dati
TELEPERIOD=5

# ============================
#  CONFIGURAZIONE SCRIPT
# ============================
MAXSIZE=500000
CELL_MIN_VOLT=2500
CELL_MAX_VOLT=3600
